import { test, expect } from "@playwright/test";

test("supervisor cadastra, estação movimenta e cancela, consulta preserva estado", async ({ page, browser }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/lotes");
  await expect(page).toHaveURL(/\/login/);
  await page.getByLabel("E-mail", { exact: true }).fill("test@example.test");
  await page.getByLabel("Senha", { exact: true }).fill("wrong-password");
  await page.getByRole("button", { name: "Entrar no painel" }).click();
  await expect(page.getByRole("alert").filter({ hasText: "E-mail ou senha incorretos." })).toBeVisible();
  await page.getByLabel("Senha", { exact: true }).fill("test-only-password");
  await page.getByRole("button", { name: "Entrar no painel" }).click();
  await expect(page.getByRole("heading", { name: "Visão geral", exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/dashboard.png", fullPage: true });
  await page.getByRole("link", { name: "Novo lote", exact: true }).click();
  await page.getByLabel("Código do lote").fill("E2E-LOTE");
  await page.getByLabel("Descrição", { exact: true }).fill("Peças para teste do fluxo completo");
  await page.getByLabel("Quantidade", { exact: true }).fill("25");
  await page.getByRole("button", { name: "Salvar e gerar URL" }).click();
  await expect(page).toHaveURL(/\/lotes\/.+\/gravar/);
  const lotId = new URL(page.url()).pathname.split("/")[2];
  await expect(page.getByRole("button", { name: "Gravar etiqueta", exact: true })).toBeDisabled();
  await page.goto("/lotes");
  await page.getByLabel("Buscar lotes").fill("E2E-LOTE");
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await page.goto("/celulares/novo");
  await page.getByLabel("Nome do celular").fill("Estação de teste");
  await page.getByLabel("Zona vinculada").selectOption({ index: 1 });
  await page.getByRole("button", { name: "Cadastrar e gerar link" }).click();
  await expect(page.getByRole("heading", { name: "Celular cadastrado" })).toBeVisible();
  const activation = await page.getByLabel("URL para copiar").inputValue();
  const stationContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const station = await stationContext.newPage();
  await station.goto(activation);
  await expect(station).toHaveURL("http://localhost:3100/estacao?ativado=1");
  await expect(station.getByText("Estação ativada com sucesso")).toBeVisible();
  const cookie = (await stationContext.cookies()).find(c => c.name === "logtrack_station");
  expect(cookie?.httpOnly).toBe(true); expect(cookie?.sameSite).toBe("Lax");
  await station.goto("http://localhost:3100/l/" + lotId);
  await expect(station.getByRole("status")).toContainText("Movido para Zona A");
  await expect(station.locator(".history-entry")).toHaveCount(1);
  await station.screenshot({ path: "test-results/leitura-mobile.png", fullPage: true });
  await station.reload();
  await expect(station.getByRole("status")).toContainText("Movimentação cancelada — Sem Zona");
  await expect(station.locator(".history-entry")).toHaveCount(2);
  const visitor = await browser.newContext();
  const consultation = await visitor.newPage();
  await consultation.goto("http://localhost:3100/l/" + lotId);
  await expect(consultation.getByRole("status")).toContainText("Modo consulta — sem celular vinculado");
  await expect(consultation.locator(".history-entry")).toHaveCount(2);
  const forbidden = await visitor.request.post("http://localhost:3100/api/zonas", { headers: { Origin: "http://localhost:3100" }, data: { nome: "Não autorizado" } });
  expect(forbidden.status()).toBe(401);
  await page.goto("/lotes/" + lotId);
  await expect(page.locator("tbody tr")).toHaveCount(2);
  await expect(page.getByRole("button", { name: "Excluir lote E2E-LOTE", exact: true })).toBeVisible();
  await page.goto("/lotes");
  const lotRow = page.getByRole("row").filter({ hasText: "E2E-LOTE" });
  await lotRow.getByRole("button", { name: "Excluir lote E2E-LOTE", exact: true }).click();
  const deletion = page.getByRole("dialog", { name: "Excluir lote E2E-LOTE", exact: true });
  await expect(deletion).toBeVisible();
  await deletion.getByRole("button", { name: "Cancelar", exact: true }).click();
  await expect(deletion).not.toBeVisible();
  await expect(lotRow).toBeVisible();
  await station.reload();
  await expect(station.getByRole("status")).toContainText("Movido para Zona A");
  const unauthorizedDelete = await visitor.request.delete("http://localhost:3100/api/lotes/" + lotId, { headers: { Origin: "http://localhost:3100" } });
  expect(unauthorizedDelete.status()).toBe(401);
  await lotRow.getByRole("button", { name: "Excluir lote E2E-LOTE", exact: true }).click();
  await deletion.getByRole("button", { name: "Confirmar exclusão", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Lote excluído com sucesso");
  await expect(lotRow).toHaveCount(0);
  await station.reload();
  await expect(station.getByRole("status")).toContainText("lote excluído");
  await expect(station.locator(".history-entry")).toHaveCount(3);
  await page.goto("/lotes/" + lotId);
  await expect(page.getByText("Lote excluído do estoque. Seu histórico continua disponível para consulta.")).toBeVisible();
  await expect(page.locator("tbody tr")).toHaveCount(3);
  await expect(page.getByRole("button", { name: "Excluir lote E2E-LOTE", exact: true })).toHaveCount(0);
  await page.goto("/celulares");
  const row = page.getByRole("row").filter({ hasText: "Estação de teste" });
  await row.getByRole("button", { name: "Desativar", exact: true }).click();
  await expect(row.getByText("Inativa", { exact: true })).toBeVisible();
  await station.reload();
  await expect(station.getByRole("status")).toContainText("Modo consulta");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await page.getByRole("button", { name: "Abrir menu" }).click();
  await page.locator("nav").getByRole("link", { name: "Zonas", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Zonas", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/zonas-mobile.png", fullPage: true });
  expect(errors).toEqual([]);
  await stationContext.close(); await visitor.close();
});
