CREATE TABLE mapas (
    id UUID NOT NULL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    imagem_url TEXT,
    largura_base INTEGER,
    altura_base INTEGER,
    criado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE estacoes_mapa (
    id UUID NOT NULL PRIMARY KEY,
    mapa_id UUID NOT NULL REFERENCES mapas(id) ON DELETE CASCADE ON UPDATE CASCADE,
    portal_id UUID NOT NULL REFERENCES portais(id) ON DELETE CASCADE ON UPDATE CASCADE,
    apelido VARCHAR(100),
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    rotacao DOUBLE PRECISION NOT NULL DEFAULT 0,
    criado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX estacoes_mapa_mapa_id_portal_id_key ON estacoes_mapa(mapa_id, portal_id);

CREATE TABLE textos_mapa (
    id UUID NOT NULL PRIMARY KEY,
    mapa_id UUID NOT NULL REFERENCES mapas(id) ON DELETE CASCADE ON UPDATE CASCADE,
    texto VARCHAR(200) NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    criado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX textos_mapa_mapa_id_idx ON textos_mapa(mapa_id);

ALTER TABLE mapas ENABLE ROW LEVEL SECURITY;
ALTER TABLE estacoes_mapa ENABLE ROW LEVEL SECURITY;
ALTER TABLE textos_mapa ENABLE ROW LEVEL SECURITY;
