CREATE TABLE zonas_mapa (
    id UUID NOT NULL PRIMARY KEY,
    mapa_id UUID NOT NULL REFERENCES mapas(id) ON DELETE CASCADE ON UPDATE CASCADE,
    zona_id UUID NOT NULL REFERENCES zonas(id) ON DELETE CASCADE ON UPDATE CASCADE,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    criado_em TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX zonas_mapa_mapa_id_zona_id_key ON zonas_mapa(mapa_id, zona_id);

ALTER TABLE zonas_mapa ENABLE ROW LEVEL SECURITY;
